openapi: 3.0.0
x-stoplight:
  id: b52es8xrbv2qa
info:
  title: FitMarket
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Member:
      title: User
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          emailVerified: true
          signUpDate: '2019-08-24'
      x-stoplight:
        id: 1h8b72owgr96k
      properties:
        id:
          type: integer
          x-stoplight:
            id: xoxy11r0lboui
        lastname:
          type: string
          x-stoplight:
            id: 2g715lturpgdh
        firstname:
          type: string
          x-stoplight:
            id: sqo2ar7vrw5lz
        email:
          type: string
          x-stoplight:
            id: pjy5otrn2hn1j
        password:
          type: string
          x-stoplight:
            id: pe0yihh1uqssl
      description: ''
    Comment:
      title: Comment
      x-stoplight:
        id: ioqe915vcp7pf
      type: object
      properties:
        id:
          type: integer
          x-stoplight:
            id: 3dcogxhsjox42
        content:
          type: string
          x-stoplight:
            id: sa2iyul3zc2ir
        date_time:
          type: string
          x-stoplight:
            id: 2n5j7mpx5ff9y
        images:
          type: array
          x-stoplight:
            id: 4s0hxq7ejkqwo
          items:
            x-stoplight:
              id: mg5qiodk1u4k4
            type: string
        note:
          type: integer
          x-stoplight:
            id: oyxinm7ts4p5t
        product:
          $ref: '#/components/schemas/Product'
          x-stoplight:
            id: yllkgs3x727f8
        user:
          $ref: '#/components/schemas/Member'
          x-stoplight:
            id: jrumut1nfda0a
        title:
          type: string
          x-stoplight:
            id: cik2ukm86pnq5
    Product:
      title: Product
      x-stoplight:
        id: hl7nec5fwdmyy
      type: object
      properties:
        id:
          type: integer
          x-stoplight:
            id: ubbx8dn0fn09x
        price:
          type: integer
          x-stoplight:
            id: dqxxaor5md129
        images:
          type: array
          x-stoplight:
            id: tdpmgwbekc7y3
          items:
            x-stoplight:
              id: qobasavfbjyi5
            type: string
        description:
          type: string
          x-stoplight:
            id: mj1cokug4sep7
        category:
          $ref: '#/components/schemas/Category'
          x-stoplight:
            id: zblfwcg4xsigk
        title:
          type: string
          x-stoplight:
            id: jzgbnuypucaoo
    Classes:
      title: Classes
      x-stoplight:
        id: sa3zc31rlfko2
      type: object
      properties:
        id:
          type: integer
          x-stoplight:
            id: x8y9s98d8j3jl
        product:
          $ref: '#/components/schemas/Product'
          x-stoplight:
            id: dhukmpf9iwoxw
        video:
          type: string
          x-stoplight:
            id: ub19yq6enqwy4
        day_time:
          type: string
          x-stoplight:
            id: 2jfb4vusoalke
        duration:
          type: integer
          x-stoplight:
            id: r65y4564olfx3
        address:
          type: string
          x-stoplight:
            id: qcbo8u7fjawwg
    Order:
      title: Order
      x-stoplight:
        id: 1dpo669joyree
      type: object
      properties:
        id:
          type: integer
          x-stoplight:
            id: t7h9qy1zuy5ye
        dateOrder:
          type: string
          x-stoplight:
            id: v1bb6nst0vp6a
        user:
          $ref: '#/components/schemas/Member'
          x-stoplight:
            id: drinky91o77m9
        products:
          type: array
          x-stoplight:
            id: pb09yw4ucngcx
          items:
            $ref: '#/components/schemas/OrderProduct'
            x-stoplight:
              id: 9mzq97bkzai6q
    OrderProduct:
      title: OrderProduct
      x-stoplight:
        id: c6qeumomwlegc
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: 347lpztzmym93
        order:
          $ref: '#/components/schemas/Order'
          x-stoplight:
            id: niaqs0u0e98gi
        product:
          $ref: '#/components/schemas/Product'
          x-stoplight:
            id: h9oni8ijhnq63
        quantity:
          type: integer
          x-stoplight:
            id: 44che7j6g22hx
    Category:
      title: Category
      x-stoplight:
        id: yecc2kc7ftvpa
      enum:
        - equipment
        - clothes
        - classes
        - nutrition
    Error:
      type: object
      title: Error
      properties:
        code:
          type: string
        description:
          type: string
